# Generated by Django 2.2 on 2019-05-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_styles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartscale',
            name='largest',
            field=models.BooleanField(default=True, help_text='Constraint by largest dimension.'),
        ),
    ]
