# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_styles', '0002_auto_20170420_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='anchor',
            field=models.IntegerField(choices=[(1, 'top-left'), (2, 'top-center'), (3, 'top-right'), (4, 'middle-left'), (5, 'middle-center'), (6, 'middle-right'), (7, 'bottom-left'), (8, 'bottom-center'), (9, 'bottom-right')], default=5),
        ),
        migrations.AlterField(
            model_name='scale',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nearest'), (1, 'Antialias'), (2, 'Bilinear'), (3, 'Bicubic')], default=1),
        ),
        migrations.AlterField(
            model_name='smartscale',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nearest'), (1, 'Antialias'), (2, 'Bilinear'), (3, 'Bicubic')], default=1),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.SlugField(max_length=127, unique=True),
        ),
    ]
