# Generated by Django 2.2 on 2019-05-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_styles', '0003_auto_20190505_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ('name',)},
        ),
    ]
